### ISSUE TITLE
Please confirm what NC_CLIENT_IP is?

### ISSUE THREAD

**Issue by programster** [h3/letsencrypt-namecheap-hook#2]
Can you please confirm what `NC_CLIENT_IP` in the README is supposed to be? Is it:
* the IP of the server the generated certificate is supposed to go on.
* the IP of the namecheap API server that is supposed to receive the request? (so i should put in the result of ping api.namecheap.com)
* something else?

**Comment by h3** [comment]
`NC_CLIENT_IP` translates to `ClientIp` on namecheap side:

https://www.namecheap.com/support/api/global-parameters.aspx

> IP address of the client accessing your application (End-user IP address)

In short, the client is where the API consumer runs .. so this is basically the IP that namecheap will see the request coming from.

Now, don't ask me why they need information they get by default when their API receive a request. Maybe to get the right IP around proxy or NAT,  I don't have a clue why they would do that.

**Comment by h3** [comment]
BTW letsencrypt.sh is deprecated, you should look this up: https://github.com/lukas2511/dehydrated

**Comment by programster** [comment]
@h3 thanks for clarifying that. Yep, im building against dehydrated assuming I can still use this hook for it.

**Comment by h3** [comment]
@programster cool let me know if it works ;)
